version: 2

project_name: collie

release:
  github:
    owner: noppaz
    name: collie

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
